apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/service-name": "billing"
    "consul.hashicorp.com/connect-service-port": "8085"
  labels:
    app: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - name: waiter
        image: vahidhedayati/beer-billing:1.118
        env:
        - name: CONSUL_HOST
          value: "consul-server"
        - name: KAFKA_HOST
          value: "kafka-service"
        - name: ZIPKIN_HOST
          value: "zipkin-deployment"
        - name: MONGO_HOST
          value: "mongodb"
        ports:
        - containerPort: 8085
