apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: waiter
        image: vahidhedayati/beer-front:
        env:
        - name: CONSUL_HOST
          value: "wondering-garfish-consul-server"
        - name: KAFKA_HOST
          value: "kafka-service"
        - name: ZIPKIN_HOST
          value: "zipkin-deployment"
        - name: MONGO_HOST
          value: "mongodb"
        ports:
        - containerPort: 
