apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  annotations:
    "consul.hashicorp.com/connect-inject": "false"
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: waiter
        image: vahidhedayati/beer-front:1.50
        env:
        - name: CONSUL_HOST
          value: "custom-consul-server"
        - name: KAFKA_HOST
          value: "kafka-service"
        - name: ZIPKIN_HOST
          value: "zipkin-deployment"
        - name: MONGO_HOST
          value: "mongodb"
        ports:
        - containerPort: 8080
