apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stock-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - http:
      paths:
        - path: /stock
          backend:
            serviceName: stock-deployment
            servicePort: 8083
