apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  labels:
    app: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - name: waiter
        image: vahidhedayati/beer-stock:1.41
        env:
        - name: CONSUL_HOST
          value: "kind-cheetah-consul-server-0"
        - name: KAFKA_HOST
          value: "kafka-service"
        - name: ZIPKIN_HOST
          value: "zipkin-deployment"
        - name: MONGO_HOST
          value: "mongodb"
        ports:
        - containerPort: 8083
