apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiter
  labels:
    app: waiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waiter
  template:
    metadata:
      labels:
        app: waiter
    spec:
      containers:
      - name: waiter
        image: vahidhedayati/beer-waiter:1.39
        env:
        - name: CONSUL_HOST
          value: "kind-cheetah-consul-server-0"
        - name: KAFKA_HOST
          value: "kafka-service"
        - name: ZIPKIN_HOST
          value: "zipkin-deployment"
        - name: MONGO_HOST
          value: "mongodb"
        ports:
        - containerPort: 8084
